### PR TITLE
Add a Travis build

### PR DESCRIPTION
**Pull request by Cantido**
At the moment of this commit, @drusepth needs to allow Travis to access
this repository for this to actually work. I submitted the request just a moment ago.

To do:
- [X] Allow Travis CI access to this repository

We're all set to merge!

### CODE REVIEW

**Comment by Cantido** [comment]
Oh, it looks like I need admin rights to flip the switch in Travis.

@drusepth, could you go to https://travis-ci.org/profile/indentlabs and flip the switch to add Travis to this repo?

While you're at it, could you turn it on for indent as well?

**Comment by drusepth** [comment]
Been trying to get it to load all evening. Will flip them both over as soon as I see something more than

screen shot 2015-12-21 at 10 12 56 pm

**Comment by Cantido** [comment]
Gotcha. That's really strange. I just checked that page myself and it loaded immediately.

**Comment by drusepth** [comment]
@Cantido Finally loaded for me. Should be flipped on now.

**Comment by Cantido** [comment]
Excellent! Now we just have a failing build to debug. I'll push back on this `ci` branch and create a pull request we can talk about before bothering the main build. It will require some configuration changes now I think, probably just setting up a test database.

**Pull request merged**
