### PR TITLE
Fix automated build

### PR DESCRIPTION
**Pull request by Cantido**
This change gets Travis up and running. I am opening a pull request because the migrations on master were not run yet, so I had to run them.

@drusepth, I know the migration is just adding a column, but I wanted to get your attention on this since you'll have to migrate your production DB. Merge at your leisure.

### CODE REVIEW

**Comment by drusepth** [comment]
Got it.

**Comment by Cantido** [comment]
And the build is now passing, fantastic! Now it's time to actually write some tests :P

**Comment by drusepth** [comment]
Got any experience with benchmarking? I don't know whether it falls into unit or integration tests, but since speed is a really important aspect of this project (it'd be nice if people could eventually upload entire novels or similar and have it respond in a reasonable time), it'd be nice to have some tests to ensure each metric can run in a certain amount of time for varying lengths of text -- and to be able to move that time bar downward as the project matures.

**Comment by Cantido** [comment]
I haven't done that before. I'm sure we could assign a timeout to some tests, though.

**Comment by Cantido** [comment]
I found [this Rails guide](http://guides.rubyonrails.org/v3.2.13/performance_testing.html) on performance testing, but i can't find any docs for Rails 4.2

**Pull request merged**
